/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.home;

import com.database.Db;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ruby
 */
public class Ac extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ac
     */
      java.sql.Date sqd;
    public Ac() {
        initComponents();
        BindCombo();
        BindC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pr = new javax.swing.JComboBox<>();
        fr = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pri = new javax.swing.JTextField();
        qt = new javax.swing.JTextField();
        mte = new javax.swing.JTextField();
        dt = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1053, 554));

        jLabel1.setText("jLabel1");

        jLabel2.setText("produit");

        jLabel3.setText("fournisseur");

        pr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prActionPerformed(evt);
            }
        });

        fr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        fr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frActionPerformed(evt);
            }
        });

        jLabel4.setText("prix");

        jLabel5.setText("qte");

        jLabel6.setText("montant");

        jLabel7.setText("date");

        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(421, 421, 421)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(41, 41, 41)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mte, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(qt, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pri, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(30, 30, 30)
                                    .addComponent(pr, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(fr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButton1)))
                .addContainerGap(575, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4))
                    .addComponent(pri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(qt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(dt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
            Acba mq = new Acba();
        HashMap<String, Integer> map = mq.populateCombo();
        int idp=map.get(pr.getSelectedItem());
               
           Acba mt = new Acba();
        HashMap<String, Integer> ju = mt.populate();
        int idf=ju.get(fr.getSelectedItem());
               
       
                float price=Float.parseFloat(pri.getText());
                
                int qte=Integer.parseInt(qt.getText());
                
                float montant=price*qte;
                
                mte.setText(Float.toString(montant));
        java.util.Date dat = dt.getDate();
     
        sqd = new java.sql.Date(dat.getTime());
                
       
           
                Acbe be=new Acbe(0,idp,idf,  price,  qte,  montant, sqd);
                Acba B=new Acba();
                B.insertD(be);
                String query="select qte,id from product where id="+idp;
                try {
                    PreparedStatement ps=Db.con.prepareStatement(query);
                    ResultSet  ms=ps.executeQuery();
                    while(ms.next()){
                        
                        int qteee=ms.getInt("qte");
                        
                        qteee=qteee+qte;
                        try{
                            String quer="update product set qte=? where id="+idp;
                            
                            PreparedStatement ts=Db.con.prepareStatement(quer);
                            ts.setInt(1,qteee);
                            ts.executeUpdate();
                            
                            
                            
                            
                            
                            
                            
                        }catch (Exception e) {
                            JOptionPane.showMessageDialog(null,""+e);
                        }
                    }
                 
            
        } catch (SQLException ex) {
            Logger.getLogger(Ac.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    /*
    private void prActionPerformed(java.awt.event.ActionEvent evt) {                                   
      int nb=pr.getSelectedIndex();
      lb.setText(String.valueOf(nb));
    }                                  
 */
    /*public void upj(){
    try {
    
    String qu="select name,id from product";
    String query="select firstname,id from fourn";
    PreparedStatement ps=Db.con.prepareStatement(query);
    ResultSet  rs=ps.executeQuery();
    while(rs.next()){
    
    String firstname=rs.getString("firstname");
    int id=rs.getInt("id");
    
    fr.addItem(firstname);
    
    }
    PreparedStatement ls=Db.con.prepareStatement(qu);
    ResultSet  hy=ls.executeQuery();
    
    while(hy.next()){
    
    String fi=hy.getString("name");
    int id=hy.getInt("id");
    
    
    Pbe comboItem = new Pbe(id,fi);
    
    
    pr.addItem(comboItem);
    
    }
    */
            
  
    /* } catch (SQLException ex) {
    JOptionPane.showMessageDialog(null,""+ex);
    }*/
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prActionPerformed
     
    }//GEN-LAST:event_prActionPerformed

    private void frActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frActionPerformed
 
    }//GEN-LAST:event_frActionPerformed

 public void BindCombo(){
        Acba mq = new Acba();
        HashMap<String, Integer> map = mq.populateCombo();
        for(String s : map.keySet()){
            pr.addItem(s);
        }
 }
         public void BindC(){
        Acba mq = new Acba();
        HashMap<String, Integer> map = mq.populate();
        for(String s : map.keySet()){
            fr.addItem(s);
        }
         }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dt;
    private javax.swing.JComboBox<String> fr;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField mte;
    private javax.swing.JComboBox<String> pr;
    private javax.swing.JTextField pri;
    private javax.swing.JTextField qt;
    // End of variables declaration//GEN-END:variables
}
