/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.home;

import com.database.Db;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author ruby
 */
public class Ve extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ve
     */
    java.sql.Date sqd;
    public Ve() {
        initComponents();
     
        BindCombo();
        BindC();
        Bind();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pr = new javax.swing.JTextField();
        iduu = new javax.swing.JComboBox<>();
        idpp = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        idcc = new javax.swing.JComboBox<>();
        qt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mt = new javax.swing.JTextField();
        da = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tp = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        rs = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dt = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        mtp = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1053, 554));

        jLabel1.setFont(new java.awt.Font("Monospaced", 2, 24)); // NOI18N
        jLabel1.setText("vente");

        jLabel2.setText("idu");

        jLabel3.setText("idp");

        jLabel4.setText("idc");

        jLabel5.setText("prix");

        iduu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));

        idpp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));

        jLabel6.setText("qte");

        idcc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));

        jLabel7.setText("montant");

        da.setText("type");

        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "partiel", "total" }));
        tp.setSelectedIndex(-1);

        jLabel8.setText("reste");

        jLabel9.setText("date");

        jLabel10.setText("montant payé");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(12, 12, 12))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(30, 30, 30)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(da)
                                    .addComponent(jLabel8))
                                .addGap(29, 29, 29)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rs, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(idpp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idcc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(qt)
                                .addComponent(mt)
                                .addComponent(pr)
                                .addComponent(iduu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tp, 0, 82, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mtp, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(dt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(579, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(iduu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idpp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(qt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(mt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(da)
                    .addComponent(tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(mtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(dt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
         Vba mq = new Vba();
        HashMap<String, Integer> map = mq.pop();
        int idu=map.get(iduu.getSelectedItem());
        
            Vba fs = new Vba();
        HashMap<String,Integer> tu = fs.populateCombo();
        int idp=tu.get(idpp.getSelectedItem());
        
        String query="select qte,id from product where id="+idp;
          try {
            PreparedStatement ps=Db.con.prepareStatement(query);
            ResultSet  ms=ps.executeQuery();
            while(ms.next()){
              
                int qteee=ms.getInt("qte");
                
                   Vba tt = new Vba();
        HashMap<String, Integer> ju = tt.populate();
        int idc=ju.get(idcc.getSelectedItem());
                 float price=Float.parseFloat(pr.getText());
       
         int qte=Integer.parseInt(qt.getText());
         if(qteee>=qte){
         float montant=price*qte;
        
        
         mt.setText(Float.toString(montant));
        
        String type=tp.getSelectedItem().toString();
        float montantp=Float.parseFloat(mtp.getText());
        if("partiel".equals(tp.getSelectedItem().toString())){
        float lo=montant-montantp; 
         rs.setText(Float.toString(lo));
        
        }
        float reste=Float.parseFloat(rs.getText());  
          
          java.util.Date dat = dt.getDate();
     
        sqd = new java.sql.Date(dat.getTime());
        Vbe be=new Vbe(0,idu,idp,idc,price,qte,montant,type,montantp,reste,sqd);
       Vba B=new Vba();
       B.insertD(be);
       qteee=qteee-qte;
         try{
            String quer="update product set qte=? where id="+idp;
          
            PreparedStatement ts=Db.con.prepareStatement(quer);
            ts.setInt(1,qteee);
            ts.executeUpdate();
           
               
                
                
                
            
          
      }catch (Exception e) {
           JOptionPane.showMessageDialog(null,""+e);
        }
            }else{
         
            JOptionPane.showMessageDialog(null,"nooooo");
         
         }               
               
             
         }
 } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,""+ex);
        }  
            
           
    
      
        
        
       
   
    }//GEN-LAST:event_jButton1ActionPerformed
 public void BindCombo(){
        Vba mq = new Vba();
        HashMap<String, Integer> map = mq.populateCombo();
        for(String s : map.keySet()){
            idpp.addItem(s);
        }
 }
    public void BindC(){
        Vba mq = new Vba();
        HashMap<String, Integer> map = mq.populate();
        for(String s : map.keySet()){
            idcc.addItem(s);
        }
         }
public void Bind(){
        Vba mq = new Vba();
        HashMap<String, Integer> map = mq.pop();
        for(String s : map.keySet()){
            iduu.addItem(s);
        }
         }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel da;
    private com.toedter.calendar.JDateChooser dt;
    private javax.swing.JComboBox<String> idcc;
    private javax.swing.JComboBox<String> idpp;
    private javax.swing.JComboBox<String> iduu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mt;
    private javax.swing.JTextField mtp;
    private javax.swing.JTextField pr;
    private javax.swing.JTextField qt;
    private javax.swing.JTextField rs;
    private javax.swing.JComboBox<String> tp;
    // End of variables declaration//GEN-END:variables
}
